'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace Wcf_Server
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="Wcf_Server.IPicSortService")>  _
    Public Interface IPicSortService
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPicSortService/TryLogin", ReplyAction:="http://tempuri.org/IPicSortService/TryLoginResponse")>  _
        Function TryLogin(ByVal loginGuid As System.Guid) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPicSortService/TryLogin", ReplyAction:="http://tempuri.org/IPicSortService/TryLoginResponse")>  _
        Function TryLoginAsync(ByVal loginGuid As System.Guid) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPicSortService/GetNewPicsList", ReplyAction:="http://tempuri.org/IPicSortService/GetNewPicsListResponse")>  _
        Function GetNewPicsList(ByVal loginGuid As System.Guid, ByVal sinceId As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPicSortService/GetNewPicsList", ReplyAction:="http://tempuri.org/IPicSortService/GetNewPicsListResponse")>  _
        Function GetNewPicsListAsync(ByVal loginGuid As System.Guid, ByVal sinceId As String) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPicSortService/GetPic", ReplyAction:="http://tempuri.org/IPicSortService/GetPicResponse")>  _
        Function GetPic(ByVal loginGuid As System.Guid, ByVal picId As String) As Byte()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPicSortService/GetPic", ReplyAction:="http://tempuri.org/IPicSortService/GetPicResponse")>  _
        Function GetPicAsync(ByVal loginGuid As System.Guid, ByVal picId As String) As System.Threading.Tasks.Task(Of Byte())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPicSortService/UploadPicDescription", ReplyAction:="http://tempuri.org/IPicSortService/UploadPicDescriptionResponse")>  _
        Function UploadPicDescription(ByVal loginGuid As System.Guid, ByVal picId As String, ByVal picData As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPicSortService/UploadPicDescription", ReplyAction:="http://tempuri.org/IPicSortService/UploadPicDescriptionResponse")>  _
        Function UploadPicDescriptionAsync(ByVal loginGuid As System.Guid, ByVal picId As String, ByVal picData As String) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPicSortService/CanUpload", ReplyAction:="http://tempuri.org/IPicSortService/CanUploadResponse")>  _
        Function CanUpload(ByVal loginGuid As System.Guid) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPicSortService/CanUpload", ReplyAction:="http://tempuri.org/IPicSortService/CanUploadResponse")>  _
        Function CanUploadAsync(ByVal loginGuid As System.Guid) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPicSortService/PutPic", ReplyAction:="http://tempuri.org/IPicSortService/PutPicResponse")>  _
        Function PutPic(ByVal loginGuid As System.Guid, ByVal picMetadata As String, ByVal picBytes() As Byte) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPicSortService/PutPic", ReplyAction:="http://tempuri.org/IPicSortService/PutPicResponse")>  _
        Function PutPicAsync(ByVal loginGuid As System.Guid, ByVal picMetadata As String, ByVal picBytes() As Byte) As System.Threading.Tasks.Task(Of Boolean)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IPicSortServiceChannel
        Inherits Wcf_Server.IPicSortService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class PicSortServiceClient
        Inherits System.ServiceModel.ClientBase(Of Wcf_Server.IPicSortService)
        Implements Wcf_Server.IPicSortService
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function TryLogin(ByVal loginGuid As System.Guid) As String Implements Wcf_Server.IPicSortService.TryLogin
            Return MyBase.Channel.TryLogin(loginGuid)
        End Function
        
        Public Function TryLoginAsync(ByVal loginGuid As System.Guid) As System.Threading.Tasks.Task(Of String) Implements Wcf_Server.IPicSortService.TryLoginAsync
            Return MyBase.Channel.TryLoginAsync(loginGuid)
        End Function
        
        Public Function GetNewPicsList(ByVal loginGuid As System.Guid, ByVal sinceId As String) As String Implements Wcf_Server.IPicSortService.GetNewPicsList
            Return MyBase.Channel.GetNewPicsList(loginGuid, sinceId)
        End Function
        
        Public Function GetNewPicsListAsync(ByVal loginGuid As System.Guid, ByVal sinceId As String) As System.Threading.Tasks.Task(Of String) Implements Wcf_Server.IPicSortService.GetNewPicsListAsync
            Return MyBase.Channel.GetNewPicsListAsync(loginGuid, sinceId)
        End Function
        
        Public Function GetPic(ByVal loginGuid As System.Guid, ByVal picId As String) As Byte() Implements Wcf_Server.IPicSortService.GetPic
            Return MyBase.Channel.GetPic(loginGuid, picId)
        End Function
        
        Public Function GetPicAsync(ByVal loginGuid As System.Guid, ByVal picId As String) As System.Threading.Tasks.Task(Of Byte()) Implements Wcf_Server.IPicSortService.GetPicAsync
            Return MyBase.Channel.GetPicAsync(loginGuid, picId)
        End Function
        
        Public Function UploadPicDescription(ByVal loginGuid As System.Guid, ByVal picId As String, ByVal picData As String) As Boolean Implements Wcf_Server.IPicSortService.UploadPicDescription
            Return MyBase.Channel.UploadPicDescription(loginGuid, picId, picData)
        End Function
        
        Public Function UploadPicDescriptionAsync(ByVal loginGuid As System.Guid, ByVal picId As String, ByVal picData As String) As System.Threading.Tasks.Task(Of Boolean) Implements Wcf_Server.IPicSortService.UploadPicDescriptionAsync
            Return MyBase.Channel.UploadPicDescriptionAsync(loginGuid, picId, picData)
        End Function
        
        Public Function CanUpload(ByVal loginGuid As System.Guid) As Boolean Implements Wcf_Server.IPicSortService.CanUpload
            Return MyBase.Channel.CanUpload(loginGuid)
        End Function
        
        Public Function CanUploadAsync(ByVal loginGuid As System.Guid) As System.Threading.Tasks.Task(Of Boolean) Implements Wcf_Server.IPicSortService.CanUploadAsync
            Return MyBase.Channel.CanUploadAsync(loginGuid)
        End Function
        
        Public Function PutPic(ByVal loginGuid As System.Guid, ByVal picMetadata As String, ByVal picBytes() As Byte) As Boolean Implements Wcf_Server.IPicSortService.PutPic
            Return MyBase.Channel.PutPic(loginGuid, picMetadata, picBytes)
        End Function
        
        Public Function PutPicAsync(ByVal loginGuid As System.Guid, ByVal picMetadata As String, ByVal picBytes() As Byte) As System.Threading.Tasks.Task(Of Boolean) Implements Wcf_Server.IPicSortService.PutPicAsync
            Return MyBase.Channel.PutPicAsync(loginGuid, picMetadata, picBytes)
        End Function
    End Class
End Namespace
